The-Ham-Project/BE

- build.gradle
- src/main/java/com/hanghae/theham/HelloController.java
- src/main/resources/logback-dev.xml
> feat: log error 슬랙에 연동

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalImageResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalImageRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
* #10 
* 함께쓰기 게시글 조회
- 로그인 기능이 추가되면 닉네임 부분을 수정해야할 수 있음
이미지가 있을 경우
```json
{
"message": "함께쓰기 게시글 조회 기능",
"data": {
"nickname": "닉네임",
"profileUrl": null,
"category": "도서",
"title": "제목입니다.",
"content": "내용입니다.",
"rentalFee": 10000,
"deposit": 10000,
"rentalImageList": [
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/dcccec6b-535c-4f89-b74e-f6e1626bb909.png",
"createdAt": "2024-03-30 17:38:12"
},
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/186bcef5-f339-42e4-a015-2fe4b47bd9d6.png",
"createdAt": "2024-03-30 17:38:12"
},
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/f7274856-351e-46b8-a9a6-b03a49fa1653.png",
"createdAt": "2024-03-30 17:38:12"
}
]
}
}
```
이미지가 없을 경우
```json
{ …
```
> feat: 함께쓰기 게시글 조회 기능

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
* #12 
- 함께쓰기 게시글 삭제 기능
- soft delete 적용
* CRUD가 완성 되면 배치 작업을 통해 일정 기간마다 게시글 삭제, 관련된 이미지 삭제 기능이 추가 될 예정
> feat: 함께쓰기 게시글 삭제 기능

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #11 
- 함께쓰기 게시글 수정 기능
- 기존에 있던 이미지를 모두 삭제
- 새로 업데이트 된 이미지를 다시 추가
- 프론트에서 업데이트 버튼을 누르면 기존 데이터 값들을 가져오게끔 해줘야 함
수정하기 전 조회 했을 때 결과 값
```json
{
"message": "함께쓰기 게시글 조회 기능",
"data": {
"nickname": "닉네임",
"profileUrl": "1234",
"category": "도서",
"title": "스프링부트 책 필요하신분~",
"content": "필요하신분 무료로 나눔해드립니다.",
"deposit": 0,
"rentalImageList": [
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/12524c83-ac3a-4e22-9883-df3ed3de7f18.png",
"createdAt": "2024-04-01 00:24:09"
},
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/27faac33-dde7-49b1-916c-b3c48f1f3f0c.png",
"createdAt": "2024-04-01 00:24:09"
}
]
}
}
```
수정 후 조회 했을 때 결과 값
```json
{
"message": "함께쓰기 게시글 조회 기능",
"data": {
"nickname": "닉네임", …
```
> feat: 함께쓰기 게시글 수정 기능

- src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
- src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
- src/main/java/com/hanghae/theham/domain/member/service/GoogleService.java
- src/main/java/com/hanghae/theham/domain/member/service/KakaoService.java
- src/main/java/com/hanghae/theham/domain/member/service/NaverService.java
- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
- src/main/java/com/hanghae/theham/global/security/JwtAuthorizationFilter.java
* #25 
- 소셜 로그인에 시큐리티 적용 시켰습니다.
- 액세스 토큰이 만료되면 401 에러를 나타냅니다.
- 401 에러가 발생하면 프론트쪽에서 캐치한 후 reissue api를 불러오면 토큰이 재발행됩니다.  
* 코드 리펙토링
> feat: 소셜 로그인 시큐리티 적용

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
- src/main/java/com/hanghae/theham/domain/rental/entity/type/CategoryType.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
* #22 
- 카테고리별 게시글 조회 기능
```json
{
"message": "함께쓰기 카테고리별 게시글 조회 기능",
"data": [
{
"nickname": "e0108496-ec69-48cc-b3b9-d6cedf902b84",
"profileUrl": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640",
"category": "생활용품",
"title": "스프링부트 책 필요하신분~",
"content": "필요하신분 무료로 나눔해드립니다.",
"deposit": 0,
"latitude": 0,
"longitude": 0,
"firstThumbnailUrl": null
},
{
"nickname": "e0108496-ec69-48cc-b3b9-d6cedf902b84",
"profileUrl": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640",
"category": "생활용품",
"title": "스프링부트 책 필요하신분~",
"content": "필요하신분 무료로 나눔해드립니다.",
"deposit": 0,
"latitude": 0,
"longitude": 0,
"firstThumbnailUrl": null
},
{
"nickname": "e0108496-ec69-48cc-b3b9-d6cedf902b84", …
```
> feat: 카테고리별 함께쓰기 게시글 조회 기능

- src/test/java/com/hanghae/theham/domain/member/service/AuthServiceTest.java
* #40 
- AuthService 테스트 코드 작성
- 리프레쉬 토큰 재발행 성공/실패
- 리프레쉬 토큰으로 로그아웃 성공/실패
> test: AuthService 테스트 코드 작성

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #38 
* 마이페이지 내가 쓴 글 목록 조회 기능
```java
{
"message": "함께쓰기 마이페이지 내가 쓴 게시글 조회 기능",
"data": {
"content": [
{
"rentalId": 4,
"profileUrl": "https://lh3.googleusercontent.com/a-/ALV-UjWipATKYI-ww0NYVBwdhrigXJBeeXX_s5E9g8hk2YhhGaE=s96-c",
"title": "우산 빌려드립니다 !",
"content": "가까운 곳에 계시는 분 우산 빌려드립니다 !",
"deposit": 0,
"firstThumbnailUrl": null
},
{
"rentalId": 3,
"profileUrl": "https://lh3.googleusercontent.com/a-/ALV-UjWipATKYI-ww0NYVBwdhrigXJBeeXX_s5E9g8hk2YhhGaE=s96-c",
"title": "정유정 소설책 필요하신분~",
"content": "완전 재미있습니다.",
"rentalFee": 100,
"deposit": 500,
"firstThumbnailUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/01f5d2b5-f0a4-4ae7-9cd9-c4f5c4c60cb4.jpeg"
}
],
"pageable": {
"pageNumber": 0,
"pageSize": 10,
"sort": {
"empty": false, …
```
> feat: 마이페이지 내가 쓴 글 조회

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #39
- RentalControllerDocs > readRentalList userDetail 추가
- RentalController > readRentalList userDetail 추가
- RentalRepository > 페이징에 거리계산 쿼리 추가
- RentalService > readRentalList에 멤버 위치 가져오는 로직 추가
* 기입 예: 예외 처리를 추가적으로 해줘야 합니다.
* 기입 예: 아직 포스트맨 테스트를 해보지 않았습니다.
* native query로 category를 비교할 때  "WHERE distance < 4 AND category=:category "에서 CategoryType 값에서 에러가 나서 category.toString()으로 캐스팅 해서 적용 
발생한 예외
```java
// 예외
```
예외가 발생한 코드
```java
// 코드
```
원인 분석
> 이러이러한 것이 원인이었다!
수정한 코드
```java
// 수정한 코드
```
> feat: 함께쓰기 위치에 따라서 쿼리

- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/scheduler/RentalScheduler.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/exception/AwsS3Exception.java
- src/main/java/com/hanghae/theham/global/exception/CustomExceptionHandler.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
* #45 
* 중복되는 부분을 함수로 만들어서 뺐습니다.
* S3 커스텀 예외처리 부분을 추가했습니다.
> refactor: Rental 관련된 내용 리팩토링

- src/main/java/com/hanghae/theham/domain/member/repository/MemberRepository.java
- src/main/java/com/hanghae/theham/domain/member/service/GoogleService.java
- src/main/java/com/hanghae/theham/domain/member/service/KakaoService.java
- src/main/java/com/hanghae/theham/domain/member/service/NaverService.java
* #44 
* 기존 UUID에서 "더함이001" 이런 방식으로 수정
> feat: 랜덤 닉네임 추가

- src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
- src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
- src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
- src/main/java/com/hanghae/theham/domain/member/entity/Member.java
- src/main/java/com/hanghae/theham/domain/member/repository/MemberRepository.java
- src/main/java/com/hanghae/theham/domain/member/service/SocialLoginService.java
- src/main/java/com/hanghae/theham/domain/member/strategy/GoogleLoginStrategy.java
- src/main/java/com/hanghae/theham/domain/member/strategy/KakaoLoginStrategy.java
- src/main/java/com/hanghae/theham/domain/member/strategy/NaverLoginStrategy.java
- src/main/java/com/hanghae/theham/domain/member/strategy/SocialLoginStrategy.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
> refactor: 소셜 로그인 전략 패턴 적용

- src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
> test : sockJs 테스트

- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
- src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
* #50 
* 메세지 전송시 Request 값 변경
* 기존 senderId(memberId) -> senderNickname(member nickname) 
* ChatRoom CreatedAt / ModifiedAt 
* Request 값 변경 하여 변경 후 동작 잘 하는지 확인하면서 메세지 같은 내용 전송하다 발견하였다.
예외가 발생한 코드
```java
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
@Entity
@Table(name = "chat_room_tbl")
public class ChatRoom extends Timestamped {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
// 중간생략 ...
@Column(name="last_chat")
private String lastChat;
// 중간생략 ...
public void updateLastChat(String message) {
this.lastChat = message;
this.modifiedAt = LocalDateTime.now();
}
}
```
원인 분석
- 같은 메세지 내용 전송시 `dirty checking` 불가로 ChatRoom 에 lastCaht update 가 안되고 있었음
수정한 코드
- CreatedAt / ModifedAt 을 ChatRoom 에 직접 생성, lastChat update 시 modifiedAt 도 현재시간으로 update 되게 하여 같은 …
>  fix : 채팅 message send request 변경 멤버Id -> 닉네임

- src/main/java/com/hanghae/theham/domain/like/controller/LikeController.java
- src/main/java/com/hanghae/theham/domain/like/controller/docs/LikeControllerDocs.java
- src/main/java/com/hanghae/theham/domain/like/dto/LikeRequestDto.java
- src/main/java/com/hanghae/theham/domain/like/dto/LikeResponseDto.java
- src/main/java/com/hanghae/theham/domain/like/entity/Like.java
- src/main/java/com/hanghae/theham/domain/like/repository/LikeRepository.java
- src/main/java/com/hanghae/theham/domain/like/service/LikeService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
* #13 
* 함께쓰기 좋아요 등록 결과
```java
{
"message": "함께쓰기 찜하기 등록 기능",
"data": {
"id": 4,
"rentalId": 3,
"createAt": "2024-04-06 09:27:19"
}
}
```
* 함께쓰기 좋아요 조회 결과
```java
{
"message": "함께쓰기 찜하기 조회 기능",
"data": {
"content": [
{
"id": 4,
"rentalId": 3
},
{
"id": 3,
"rentalId": 2
},
{
"id": 2,
"rentalId": 1
}
],
"pageable": {
"pageNumber": 0,
"pageSize": 10,
"sort": {
"empty": false,
"sorted": true,
"unsorted": false
},
"offset": 0,
"unpaged": false,
"paged": true
},
"size": 10,
"number": 0,
"sort": {
"empty": false,
"sorted": true,
"unsorted": false
},
"first": true,
"last": true,
"numberOfElements": 3,
"empty": false
}
}
```
* 함께쓰기 좋아요 삭제 결과
좋아요 삭제 전 DB
좋아요 삭제 후 DB
> feat: 함께쓰기 좋아요 등록/삭제/조회 기능

- .ebextensions/00-set-timezone.config
> chore: EC2 Timezone 설정

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
> test: 함께쓰기 게시글 작성 테스트 코드

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
> test: 함께쓰기 게시글 수정 테스트 코드

- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
> test: 함께쓰기 게시글 삭제 테스트 코드

- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
> test: 함께쓰기 게시글 조회 테스트 코드

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
#62 
* 게시글 id, 이미지 url, 제목, 작성자를 검색어 LIKE(%searchValue%)로 찾는 기능 추가
* RentalSearchService 추가
* 적용 시 프론트와 테스트 필요
* 기입 예 - 1. ~~ 발생한 예외 이름 또는 뭐 하다가 예외 발생했다. 기록
발생한 예외
```java
// 예외
```
예외가 발생한 코드
```java
// 코드
```
원인 분석
> 이러이러한 것이 원인이었다!
수정한 코드
```java
// 수정한 코드
```
> feat: 함께쓰기 검색기능 추가 / 글id, 제목, 작성자, 사진url

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #86 
* 함께쓰기 서비스 레이어 페이징 버그 수정
> refactor: 함께쓰기 서비스 레이어 리팩토링 및 오류 수정

- src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
- src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
- src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
- src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
- src/test/java/com/hanghae/theham/domain/member/service/MemberServiceTest.java
* #88 
* 회원 정보 조회 기능
```json
{
"message": "회원 정보 조회 기능",
"data": {
"nickname": "더함이001",
"email": "suhwan@kakao.com",
"profileUrl": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640"
}
}
```
> feat: 회원 정보 조회 기능 추가

- build.gradle
- src/test/java/com/hanghae/theham/domain/member/repository/MemberRepositoryTest.java
> test: Member Repository 테스트 코드 작성

- build.gradle
- src/main/java/com/hanghae/theham/domain/chat/controller/ChatController.java
- src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
- src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatControllerDocs.java
- src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatResponseDto.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
- src/main/java/com/hanghae/theham/global/config/WebSocketConfig.java
- src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
* #61 
* socket 초기 handshke 시 access 토큰 검증하여 사용자 검증, 검증된 사용자가 아니라면 소켓 등록 불가.
* 메세지 전송시 Secrutiy의 Principle 을 사용하여 사용자 정보 사용 할 수 있도록 변경
* 채팅방 생성시 기존 채팅방이 존재한다면, 기존 채팅방 번호 반환하도록 수정
* 채팅방 상세조회 response 에 senderProfileImage 추가(front 요청)
* socket 예외처리
* 채팅 전체목록, 채팅 상세 조회(대화내역) 페이징 처리
* 채팅방 삭제
****
🥔 **api/v1/chat-rooms/{roomId}**
```json
{
"message": "채팅방 상세 조회 기능",
"data": {
"toUserNickname": "구글라미",
"toUserProfileImage": "https://lh3.googleusercontent.com/a-/ALV-UjXgvDeSrZcjJFCQENOwdQjKj2Q4MPV5PN47wvK6s-pM=s96-c",
"senderProfileImage": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640",
"chatReadResponseDtoList": []
}
}
```
🥔 **api/v1/chat-rooms**
기존 request 
```java
public static class ChatSendMessageRequestDto {
@NotBlank(message = "채탱 보내는 멤버의 …
```
> feat: 채팅 토큰 인증 추가

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
* #94 
* 보증금, 대여비 1백만원 미만으로 설정
```json
{
"status": false,
"message": "유효성 검사 실패",
"data": {
"rentalFee": "금액은 1백만원 미만이어야 합니다."
}
}
```
> feat: 대여비, 보증금 1백만원 금액 제한

- src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
- src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
- src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
- src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
* #96 
- 로그인 한 회원의 위도, 경도 값 체크
- 위도 or 경도 값 중에서 하나라도 0일 경우 false
```json
{
"message": "회원 좌표 검사 기능",
"data": {
"isCheck": false
}
}
```
> feat: 로그인 했을 시 회원의 위도, 경도 값 체크

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
* #98 
* 함께쓰기 상세 페이지 지역구 추가
```json
{
"message": "함께쓰기 게시글 조회 기능",
"data": {
"rentalId": 7,
"nickname": "더함이001",
"profileUrl": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640",
"category": "생활용품",
"title": "스프링부트 책 필요하신분~",
"content": "필요하신분 무료로 나눔해드립니다.",
"rentalFee": 999999,
"deposit": 0,
"district": "성남시 수정구",
"rentalImageList": []
}
}
```
> feat: 함께쓰기 상세 페이지 지역구 응답 값 추가

- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
* #100 
* 카테고리에서 ALL로 작성할 수 있었던 버그를 수정
```json
{
"status": false,
"message": "카테고리가 올바르지 않습니다.",
"data": null
}
```
> fix: 카테고리 ALL로 작성 가능했던 버그 수정

- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
* #74 
- 함께쓰기 마이페이지 내가 쓴 글 조회 테스트 코드 작성
- 이미지 첨부 O, X
> test: 함께쓰기 마이페이지 내가 쓴 글 조회 테스트 코드

- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
* #71 
- 함께쓰기 카테고리별 게시글 조회 테스트 코드
- 로그인 X, 모든 카테고리
- 로그인 X, 특정 카테고리
- 로그인 O, 모든 카테고리
- 로그인 O, 특정 카테고리
> test: 함께쓰기 카테고리별 게시글 조회 테스트 코드

- build.gradle
- src/test/java/com/hanghae/theham/domain/member/repository/MemberRepositoryTest.java
- src/test/java/com/hanghae/theham/domain/rental/repository/RentalRepositoryTest.java
> test: RentalRepository 테스트 코드 작성

- src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
- src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomRequestDto.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
* #93 
* 채팅 전체 목록 조회 페이징 추가
* 채팅 상세 목록 조회 페이징 추가
**🥔/api/v1/chat-rooms?page=2&size=10** - 회원의 전체 채팅방 목록 조회
```json
{
"message": "회원 자신의 채팅방 목록 조회 기능",
"data": [
{
"chatRoomId": 9,
"toMemberId": 3,
"toMemberNickName": "더함이003",
"toMemberProfileUrl": "https://lh3.googleusercontent.com/a-/ALV-UjXagpbRgc2zd5Kylb2mM9AavPAFVhK-lJdWx4C7IbFAadXEsg=s96-c",
"lastMessage": null,
"lastMessageTime": null
},
{
"chatRoomId": 10,
"toMemberId": 3,
"toMemberNickName": "더함이003",
"toMemberProfileUrl": "https://lh3.googleusercontent.com/a-/ALV-UjXagpbRgc2zd5Kylb2mM9AavPAFVhK-lJdWx4C7IbFAadXEsg=s96-c",
"lastMessage": null,
"lastMessageTime": null
},
{
"chatRoomId": 11,
"toMemberId": 3,
"toMemberNickName": "더함이003",
"toMemberProfileUrl": …
```
> feat: 채팅 페이징 처리 추가

- build.gradle
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalImageResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalLikeResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/config/RedisConfig.java
* #108 
- 함께쓰기 게시글 Redis를 이용해서 캐싱 작업
- Redis에 저장 되는 시간은 30분으로 설정
- 최초 MySQL에서 조회 후 Redis에 저장
적용 전
적용 후
조회 속도가 201ms -> 12ms로 94.03% 대폭 감소
> feat: 함께쓰기 게시글 캐싱 작업

- src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
- src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
* #110 
* 프론트 요청으로 현재페이지, 전체페이지 response 추가
**🥔/api/v1/chat-rooms?page=2&size=10** - 회원의 전체 채팅방 목록 조회
```json
{
"message": "회원 자신의 채팅방 목록 조회 기능",
"data": {
"totalPage": 3,
"currentPage": 2,
"chatRoomListResponseDto": [
{
"chatRoomId": 9,
"toMemberId": 3,
"toMemberNickName": "더함이003",
"toMemberProfileUrl": "https://lh3.googleusercontent.com/a-/ALV-UjXagpbRgc2zd5Kylb2mM9AavPAFVhK-lJdWx4C7IbFAadXEsg=s96-c",
"lastMessage": null,
"lastMessageTime": null
},
{
"chatRoomId": 10,
"toMemberId": 3,
"toMemberNickName": "더함이003",
"toMemberProfileUrl": "https://lh3.googleusercontent.com/a-/ALV-UjXagpbRgc2zd5Kylb2mM9AavPAFVhK-lJdWx4C7IbFAadXEsg=s96-c",
"lastMessage": null,
"lastMessageTime": null
},
{
"chatRoomId": 11,
"toMemberId": 3,
"toMemberNickName": "더함이003",
"toMemberProfileUrl": …
```
> feat: 채팅 채팅목록, 채팅 상세 현재 페이지, 전체 페이지 response 추가

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
* #118 
* 로그인 O, 내가 작성한 게시글일 경우 isChatButton = false
* 로그인 O, 내가 작성하지 않은 게시글일 경우 isChatButton = true
* 로그인 X isChatButton = true
테스트 코드를 통해 결과를 확인했습니다.
> feat: 함께쓰기 상세 페이지 채팅하기 버튼 표시 유무

- src/main/java/com/hanghae/theham/domain/chat/controller/ChatRoomController.java
- src/main/java/com/hanghae/theham/domain/chat/controller/docs/ChatRoomControllerDocs.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/hanghae/theham/domain/chat/entity/Chat.java
- src/main/java/com/hanghae/theham/domain/chat/entity/ChatRoom.java
- src/main/java/com/hanghae/theham/domain/chat/entity/type/VisibleType.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRepository.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
* #33 
* 채팅방 나가기 추가
* A - B 참여 채팅방, 모두 채팅방에 나가지 않은 상태, 
* `B 나가기 실행` A가 `reJoin` 했을 것을 고려하여 `B만 볼 수 있는 메세지 삭제` / `BOTH`(모두 볼 수 있는 메세지) 는 가시성 `ONLY_A` 로 업데이트
```        
List<Chat> deleteChatList = chatRepository.findByChatRoomAndVisible(chatRoom, isSender ? VisibleType.ONLY_SENDER : VisibleType.ONLY_RECEIVER);
chatRepository.deleteAll(deleteChatList);
List<Chat> chatList = chatRepository.findByChatRoomAndVisible(chatRoom, VisibleType.BOTH);
chatList.forEach(chat -> {
chat.updateChatVisible(isSender ? VisibleType.ONLY_RECEIVER : VisibleType.ONLY_SENDER);
});
```
*  A - B 참여 채팅방, 한명 이미 나간상태 -> 해당 채팅방에 있는 메세지와, 채팅방을 모두 삭제
* 회원의 채팅방 나간 상태( `isDeleted` ) 상태에 따른 채팅 전체목록, 상세 목록 조회 조건 변경
* A - B 참여 채팅방
* A가 나간다 - B는 채팅방 유지. 이후 A의 `reJoin` 과 메세지를 주고받는 일이 있었다고 할때.
* B가 조회 가능한 메세지 : VisibleType = …
> feat: 채팅 채팅방 나가기 기능 추가

- src/main/java/com/hanghae/theham/domain/rental/controller/RentalController.java
- src/main/java/com/hanghae/theham/domain/rental/controller/docs/RentalControllerDocs.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
* #125 
- 함께쓰기에 개수(count) 반환을 추가했습니다.
- 페이지 개수가 아니라 총 개수를 반환합니다.
```json
{
"message": "함께쓰기 검색 기능",
"data": {
"count": 6,
"searchResponseList": [
{
"rentalId": 1,
"nickname": "더함이001",
"profileUrl": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640",
"category": "전자제품",
"title": "스프링부트 책 필요하신분~",
"content": "필요하신분 무료로 나눔해드립니다.",
"deposit": 0,
"latitude": 37.123,
"longitude": 127.1565209,
"district": "용산구",
"rentalImageList": [
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/fb0359a8-22f5-4864-b5e4-0243bc066bef.png",
"createdAt": "2024-04-11 01:10:44"
}
]
}
]
}
}
```
> feat: 함께쓰기 검색 기능 개수 반환 추가

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #23 
* 썸네일 처리하는 기능 추가
* 이미지를 등록하면 Lambda에서 썸네일 처리하는 함수가 실행
> feat: 썸네일 처리 기능 추가

- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
> fix: 게시글 조회 Delete 적용

- build.gradle
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/entity/Rental.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalDistanceRepository.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalSearchService.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/test/java/com/hanghae/theham/domain/rental/repository/RentalRepositoryTest.java
- src/test/java/com/hanghae/theham/domain/rental/service/RentalServiceTest.java
* #135 
* native로 작성된 sql문을 hibernate-spatial을 이용해서 jpa로 변경했습니다.
> refactor: Hibernate Spatial 적용하기

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalRequestDto.java
- src/main/java/com/hanghae/theham/domain/rental/repository/RentalImageRepository.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #140 
- 함께쓰기 게시글 수정 로직 변경
- 기존 이미지는 url로 받아오기
- 추가된 이미지는 multipartfile로 받아오기
> refactor: 함께쓰기 게시글 수정 로직 리펙토링

- src/main/java/com/hanghae/theham/global/util/BadWordFilteringUtil.java
* #145 
* 배포 환경에서 500 에러 뜨던 현상 수정
> fix: 욕설 필터링 추가 후 배포 환경에서 500 에러 수정

- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRequestDto.java
- src/main/resources/badwords.txt
* #147 
* 추가해주신 욕설 필터링 API 채팅 부분에도 적용하였습니다.
> feat: 채팅 욕설 필터링 추가

- src/main/java/com/hanghae/theham/domain/rental/service/RentalCachingService.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #153 
* 페이지에 적용 되어있던 캐싱 처리를 제거했습니다.
> fix: 함께쓰기 페이징 캐싱 처리 된거 제거

- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
> fix: cors 설정 변경

- src/main/java/com/hanghae/theham/domain/chat/controller/ChatController.java
- src/main/java/com/hanghae/theham/domain/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/hanghae/theham/domain/chat/repository/ChatRoomRepository.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatRoomService.java
- src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
- src/main/java/com/hanghae/theham/domain/notification/controller/NotificationController.java
- src/main/java/com/hanghae/theham/domain/notification/controller/docs/NotificationControllerDocs.java
- src/main/java/com/hanghae/theham/domain/notification/dto/NotificationResponseDto.java
- src/main/java/com/hanghae/theham/domain/notification/dto/type/NotificationType.java
- src/main/java/com/hanghae/theham/domain/notification/repository/EmitterRepository.java
- src/main/java/com/hanghae/theham/domain/notification/service/NotificationService.java
- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
* #136 
* #137 
1. `front` 단에서 로그인 시 `SSE` 연결 - 회원의 전체 안읽은 메세지 수 전송
**🥔NotificationService.java _ SSE 첫 CONNECTION**
```java
// SSE 처음 구독, 초기 구독하고 연결되면 client에 안읽은 전체 메세지 수 전송 
public SseEmitter subscribe(String email) {
Member member = validateMember(email);
Long memberId = member.getId();
String emitterId = createTimeIncludeId(memberId);
SseEmitter emitter = createEmitter(emitterId);
NotificationCreateResponseDto responseDto = new NotificationCreateResponseDto(getTotalUnreadMessagesCount(member));
sendToClient(emitter, emitterId, ResponseDto.success(NotificationType.CONNECTED.getMessage(), responseDto));
return emitter;
}
// client 에 emitter 이벤트 전송
private void sendToClient(SseEmitter emitter, String emitterId, Object data) {
try {
emitter.send(SseEmitter.event()
.id(emitterId) …
```
> feat: SSE를 통한 채팅방 갱신 기능 & 새로운 메세지 알림 기능 추가

- src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
- src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
- src/main/java/com/hanghae/theham/domain/member/dto/MemberRequestDto.java
- src/main/java/com/hanghae/theham/domain/member/entity/Member.java
- src/main/java/com/hanghae/theham/domain/member/repository/MemberRepository.java
- src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
- src/main/java/com/hanghae/theham/global/service/S3Service.java
* #162 
- 회원 정보 수정 기능
- 닉네임과 프로필 사진을 변경할 수 있읍니다.
- 렌탈 부분과 중복되는 s3 기능들을 s3 service로 분리했읍니다.
> feature: 회원 정보 수정 기능

- src/main/java/com/hanghae/theham/domain/member/dto/MemberRequestDto.java
- src/main/java/com/hanghae/theham/global/config/SecurityConfig.java
> fix: 닉네임 수정 API 시큐리티 적용

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalLikeResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #170 
- 함께쓰기 좋아요 조회 기능
- isLike 필드로 조회할 수 있습니다.
```json
{
"message": "함께쓰기 게시글 조회 기능",
"data": {
"rentalId": 2,
"nickname": "더함이",
"profileUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/profiles/225c7b91-2c75-466b-8ef7-27732353ff42.jpg",
"category": "BOOK",
"title": "스프링 부트 + AWS 책 필요하신분?",
"content": "좀 오래되긴 했지만 나름 도움이 된답니다.\n필요하신분 연락 주세요 ~",
"rentalFee": 1000,
"deposit": 4000,
"district": "성동구",
"isChatButton": true,
"isLike": false,
"rentalImageList": [
{
"imageUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/rentals/93b39119-fa21-4de2-9ee5-076885f1f343.jpeg",
"createdAt": "2024-04-25 20:37:46"
}
]
}
}
```
> feat: 함께쓰기 좋아요 조회 기능

- src/main/java/com/hanghae/theham/domain/rental/service/RentalLikeService.java
* #172 
* 좋아요로 인해 캐싱된 데이터가 일치하지 않던 오류를 수정
> fix: 함께쓰기 좋아요 기능 Redis 정합성 수정

- src/main/java/com/hanghae/theham/domain/member/controller/MemberController.java
- src/main/java/com/hanghae/theham/domain/member/controller/docs/MemberControllerDocs.java
- src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
- src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
* #174 
- 닉네임 중복 검사 기능
```json
{
"message": "회원 닉네임 중복 검사 기능",
"data": {
"isCheck": true
}
}
```
> feat: 회원 닉네임 중복 검사 기능

- src/main/java/com/hanghae/theham/domain/rental/dto/RentalResponseDto.java
- src/main/java/com/hanghae/theham/domain/rental/service/RentalService.java
* #176 
* 함께쓰기 목록에 좋아요 표시
```json
{
"message": "함께쓰기 카테고리별 게시글 조회 기능",
"data": [
{
"rentalId": 132,
"nickname": "더함이",
"profileUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/profiles/225c7b91-2c75-466b-8ef7-27732353ff42.jpg",
"title": "설계도 공유합니다.",
"content": "안녕하세요.\n설계도 공유 해봅니다.",
"rentalFee": 10000,
"deposit": 10000,
"firstThumbnailUrl": "https://theham-bucket2.s3.ap-northeast-2.amazonaws.com/rentals/dc45eb75-9e13-4670-9d9b-3bedbcc35123.png",
"district": "동대문구",
"isLike": false
},
{
"rentalId": 131,
"nickname": "더함이",
"profileUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/profiles/225c7b91-2c75-466b-8ef7-27732353ff42.jpg",
"title": "얼음 빌려드립니다.",
"content": "날씨가 더워져서 얼음 나눔해드립니다.",
"deposit": 0,
"firstThumbnailUrl": …
```
> feat: 함께쓰기 목록에 좋아요 표시 기능

- src/main/java/com/hanghae/theham/domain/member/dto/MemberResponseDto.java
- src/main/java/com/hanghae/theham/domain/member/service/MemberService.java
* #178 
* 회원 정보에서 내 위치 값 반환
```json
{
"message": "회원 정보 조회 기능",
"data": {
"nickname": "더함이",
"email": "suhwan@kakao.com",
"profileUrl": "https://theham-bucket.s3.ap-northeast-2.amazonaws.com/profiles/225c7b91-2c75-466b-8ef7-27732353ff42.jpg",
"district": "공주시"
}
}
```
> feat: 내정보 위치 값 반환

- src/main/java/com/hanghae/theham/domain/chat/service/ChatService.java
- src/main/java/com/hanghae/theham/global/exception/ErrorCode.java
- src/main/java/com/hanghae/theham/global/websocket/WebSocketInterceptor.java
- src/main/java/com/hanghae/theham/global/websocket/dto/MessageErrorResponse.java
- src/main/java/com/hanghae/theham/global/websocket/exception/CustomMessageExceptionHandler.java
- src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketException.java
- src/main/java/com/hanghae/theham/global/websocket/exception/WebSocketExceptionHandler.java
* #182 
- stomp 예외 발생시 http 상태코드 반환하던 것을 ErrorCode name 을 반환하도록 변경하였습니다.
> refactor: 채팅 예외 발생시 HTTP 에러코드 반환 -> ErrorCode name 반환
